name: MLOps pipeline
on:
  workflow_dispatch:
    inputs:
      run_processing:
        description: 'Run data processing'
        required: false
        default: 'false'

jobs:
  data_processing:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.run_processing == 'true' || github.event.inputs.run_all == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: { python-version: '3.10' }
      - run: pip install -r requirements.txt
      - run: python scripts/process_data.py --out processed/
      - uses: actions/upload-artifact@v4
        with:
          name: process_data
          path: processed/

  model_training:
    runs-on: ubuntu-latest
    needs: data_processing
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - uses: actions/download-artifact@v4
        with: { name: process_data, path: data/ }
      - run: pip install -r requirements.txt
      - run: |
          mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db &
          ./scripts/wait-for-mlflow.sh
      - run: python train.py --data data/processed/ --out model/
      - uses: actions/upload-artifact@v4
        with: { name: model_artifact, path: model/ }

  build_and_publish:
    runs-on: ubuntu-latest
    needs: model_training
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with: { name: model_artifact, path: app/model }
      - run: |
          SHORT_SHA=$(git rev-parse --short=7 HEAD)
          docker build -t myorg/house-price:$SHORT_SHA -t myorg/house-price:latest .
          CID=$(docker run -d -p 8000:80 myorg/house-price:$SHORT_SHA)
          curl -f http://localhost:8000/health
          docker rm -f $CID
      - run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: |
          docker push myorg/house-price:$SHORT_SHA
          docker push myorg/house-price:latest
