name: MLOps pipeline
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      run_processing:
        description: 'Run data processing (when manually triggered)'
        required: false
        default: 'false'
      run_training:
        description: 'Run training (when manually triggered)'
        required: false
        default: 'false'
      run_build:
        description: 'Run build & publish (when manually triggered)'
        required: false
        default: 'false'

env:
  IMAGE_REPO: myorg/house-price            # <--- replace with your registry/repo
  IMAGE_LATEST_TAG: latest

jobs:
  # ----------------------------
  # Data processing: produce processed/ and preprocessor artifact
  # ----------------------------
  data_processing:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.run_processing == 'true') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run data processing
        run: |
          mkdir -p processed preprocessor
          # example call - replace with your real script invocation
          python scripts/process_data.py --out processed/
          # ensure preprocessor file exists (script should produce it)
          ls -la processed || true

      - name: Upload processed artifact
        uses: actions/upload-artifact@v4
        with:
          name: process_data
          path: |
            processed/

      - name: (optional) Upload preprocessor as artifact
        uses: actions/upload-artifact@v4
        with:
          name: preprocessor
          path: |
            preprocessor/

  # ----------------------------
  # Model training: depends on data_processing
  # ----------------------------
  model_training:
    runs-on: ubuntu-latest
    needs: data_processing
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.run_training == 'true') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Download processed data
        uses: actions/download-artifact@v4
        with:
          name: process_data
          path: data/

      - name: (optional) Download preprocessor
        uses: actions/download-artifact@v4
        with:
          name: preprocessor
          path: data/preprocessor/

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Start MLflow (local) + wait until ready
        run: |
          # if you have a remote MLflow server, skip this and set MLFLOW_TRACKING_URI env instead
          mlflow server --host 127.0.0.1 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns &> mlflow.log &
          echo "Waiting for mlflow to be ready..."
          for i in {1..30}; do
            if curl -sS http://127.0.0.1:5000 >/dev/null 2>&1; then
              echo "mlflow up"
              break
            fi
            sleep 2
          done
          tail -n +1 mlflow.log || true

      - name: Train model
        run: |
          mkdir -p model
          python train.py --data data/processed/ --out model/
          ls -la model

      - name: Package model artifact
        run: |
          # ensure there's a deterministic artifact to upload (tar.gz or zip)
          if [ -d model ]; then
            tar -czf model/model.tar.gz -C model .
          fi
          ls -la model

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: model_artifact
          path: model/

  # ----------------------------
  # Build / Test / Push image
  # - downloads model artifact into build context (app/model)
  # - builds image (locally/load), runs health check, then pushes tags (short SHA + latest)
  # ----------------------------
  build_and_publish:
    runs-on: ubuntu-latest
    needs: model_training
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.run_build == 'true') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download model artifact into app/model
        uses: actions/download-artifact@v4
        with:
          name: model_artifact
          path: app/model

      - name: Prepare build context (ensure model is in app/model and preprocessor if needed)
        run: |
          mkdir -p app/model
          # if artifact produced model/model.tar.gz, extract into app/model
          if [ -f app/model/model.tar.gz ]; then
            tar -xzf app/model/model.tar.gz -C app/model || true
          fi
          # ensure Dockerfile exists - replace with your own Dockerfile if necessary
          if [ ! -f Dockerfile ]; then
            cat > Dockerfile <<'DOCK'
FROM python:3.11-slim
WORKDIR /app
COPY . /app
RUN pip install -r requirements.txt
EXPOSE 80
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
DOCK
          fi
          ls -R app || true

      - name: Set short SHA env
        run: echo "SHORT_SHA=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

      - name: Setup Buildx (for docker/build-push-action)
        uses: docker/setup-buildx-action@v2

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image (load into runner) — used for testing container locally
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ env.IMAGE_REPO }}:${{ env.SHORT_SHA }}
          push: false
          load: true    # load image into local docker daemon for testing

      - name: Run container (test health endpoint)
        run: |
          set -euo pipefail
          IMAGE=${{ env.IMAGE_REPO }}:${{ env.SHORT_SHA }}
          docker run -d --name test_api -p 8000:80 "$IMAGE"
          # wait for container to boot and probe /health
          echo "Waiting for service to become healthy..."
          for i in {1..30}; do
            if curl -sS http://localhost:8000/health >/dev/null 2>&1; then
              echo "Service healthy"
              break
            fi
            sleep 2
          done
          # final health check (fail job if endpoint returns non-200)
          curl -f http://localhost:8000/health
        finally: |
          docker rm -f test_api || true

      - name: Push image (short SHA + latest) — only if health passed
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_REPO }}:${{ env.SHORT_SHA }}
            ${{ env.IMAGE_REPO }}:${{ env.IMAGE_LATEST_TAG }}

      - name: Confirm pushed image
        run: |
          echo "Pushed: ${{ env.IMAGE_REPO }}:${{ env.SHORT_SHA }} and ${{ env.IMAGE_REPO }}:${{ env.IMAGE_LATEST_TAG }}"

